In [1]:
# importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#importing the dataset
train_set = pd.read_csv("train.csv")
test_sets = pd.read_csv("test.csv")


In [3]:
train_set 

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [4]:
test_sets

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [5]:
train_set  = train_set .drop(['PassengerId','Name','Cabin','Ticket',], axis=1)


In [6]:
train_set  


Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  22.0      1      0    7.2500        S
1           1       1  female  38.0      1      0   71.2833        C
2           1       3  female  26.0      0      0    7.9250        S
3           1       1  female  35.0      1      0   53.1000        S
4           0       3    male  35.0      0      0    8.0500        S
5           0       3    male   NaN      0      0    8.4583        Q
6           0       1    male  54.0      0      0   51.8625        S
7           0       3    male   2.0      3      1   21.0750        S
8           1       3  female  27.0      0      2   11.1333        S
9           1       2  female  14.0      1      0   30.0708        C
10          1       3  female   4.0      1      1   16.7000        S
11          1       1  female  58.0      0      0   26.5500        S
12          0       3    male  20.0      0      0    8.0500        S
13          0       3    male  39.0      1      5   31.2750        S
14          0       3  female  14.0      0      0    7.8542        S
15          1       2  female  55.0      0      0   16.0000        S
16          0       3    male   2.0      4      1   29.1250        Q
17          1       2    male   NaN      0      0   13.0000        S
18          0       3  female  31.0      1      0   18.0000        S
19          1       3  female   NaN      0      0    7.2250        C
20          0       2    male  35.0      0      0   26.0000        S
21          1       2    male  34.0      0      0   13.0000        S
22          1       3  female  15.0      0      0    8.0292        Q
23          1       1    male  28.0      0      0   35.5000        S
24          0       3  female   8.0      3      1   21.0750        S
25          1       3  female  38.0      1      5   31.3875        S
26          0       3    male   NaN      0      0    7.2250        C
27          0       1    male  19.0      3      2  263.0000        S
28          1       3  female   NaN      0      0    7.8792        Q
29          0       3    male   NaN      0      0    7.8958        S
..        ...     ...     ...   ...    ...    ...       ...      ...
861         0       2    male  21.0      1      0   11.5000        S
862         1       1  female  48.0      0      0   25.9292        S
863         0       3  female   NaN      8      2   69.5500        S
864         0       2    male  24.0      0      0   13.0000        S
865         1       2  female  42.0      0      0   13.0000        S
866         1       2  female  27.0      1      0   13.8583        C
867         0       1    male  31.0      0      0   50.4958        S
868         0       3    male   NaN      0      0    9.5000        S
869         1       3    male   4.0      1      1   11.1333        S
870         0       3    male  26.0      0      0    7.8958        S
871         1       1  female  47.0      1      1   52.5542        S
872         0       1    male  33.0      0      0    5.0000        S
873         0       3    male  47.0      0      0    9.0000        S
874         1       2  female  28.0      1      0   24.0000        C
875         1       3  female  15.0      0      0    7.2250        C
876         0       3    male  20.0      0      0    9.8458        S
877         0       3    male  19.0      0      0    7.8958        S
878         0       3    male   NaN      0      0    7.8958        S
879         1       1  female  56.0      0      1   83.1583        C
880         1       2  female  25.0      0      1   26.0000        S
881         0       3    male  33.0      0      0    7.8958        S
882         0       3  female  22.0      0      0   10.5167        S
883         0       2    male  28.0      0      0   10.5000        S
884         0       3    male  25.0      0      0    7.0500        S
885         0       3  female  39.0      0      5   29.1250        Q
886         0       2    male  27.0      0      0   13.0000        S
887

In [7]:
test_set  = test_sets .drop(['PassengerId','Name','Cabin','Ticket',], axis=1)
test_set

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
5         3    male  14.0      0      0    9.2250        S
6         3  female  30.0      0      0    7.6292        Q
7         2    male  26.0      1      1   29.0000        S
8         3  female  18.0      0      0    7.2292        C
9         3    male  21.0      2      0   24.1500        S
10        3    male   NaN      0      0    7.8958        S
11        1    male  46.0      0      0   26.0000        S
12        1  female  23.0      1      0   82.2667        S
13        2    male  63.0      1      0   26.0000        S
14        1  female  47.0      1      0   61.1750        S
15        2  female  24.0      1      0   27.7208        C
16        2    male  35.0      0      0   12.3500        Q
17        3    male  21.0      0      0    7.2250        C
18        3  female  27.0      1      0    7.9250        S
19        3  female  45.0      0      0    7.2250        C
20        1    male  55.0      1      0   59.4000        C
21        3    male   9.0      0      1    3.1708        S
22        1  female   NaN      0      0   31.6833        S
23        1    male  21.0      0      1   61.3792        C
24        1  female  48.0      1      3  262.3750        C
25        3    male  50.0      1      0   14.5000        S
26        1  female  22.0      0      1   61.9792        C
27        3    male  22.5      0      0    7.2250        C
28        1    male  41.0      0      0   30.5000        S
29        3    male   NaN      2      0   21.6792        C
..      ...     ...   ...    ...    ...       ...      ...
388       3    male  21.0      0      0    7.7500        Q
389       3    male   6.0      3      1   21.0750        S
390       1    male  23.0      0      0   93.5000        S
391       1  female  51.0      0      1   39.4000        S
392       3    male  13.0      0      2   20.2500        S
393       2    male  47.0      0      0   10.5000        S
394       3    male  29.0      3      1   22.0250        S
395       1  female  18.0      1      0   60.0000        S
396       3    male  24.0      0      0    7.2500        Q
397       1  female  48.0      1      1   79.2000        C
398       3    male  22.0      0      0    7.7750        S
399       3    male  31.0      0      0    7.7333        Q
400       1  female  30.0      0      0  164.8667        S
401       2    male  38.0      1      0   21.0000        S
402       1  female  22.0      0      1   59.4000        C
403       1    male  17.0      0      0   47.1000        S
404       1    male  43.0      1      0   27.7208        C
405       2    male  20.0      0      0   13.8625        C
406       2    male  23.0      1      0   10.5000        S
407       1    male  50.0      1      1  211.5000        C
408       3  female   NaN      0      0    7.7208        Q
409       3  female   3.0      1      1   13.7750        S
410       3  female   NaN      0      0    7.7500        Q
411       1  female  37.0      1      0   90.0000        Q
412       3  female  28.0      0      0    7.7750        S
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [8]:
#  taking care of categorical data
train_set.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [9]:
#from sklearn.preprocessing import Imputer
#imputer = Imputer(missing_values='NAN',strategy = "mean", axis =0)
#imputer = imputer.fit(train_set[])

train_set['Age'] = train_set['Age'].fillna(train_set['Age'].mean())
train_set['Embarked'] = train_set['Embarked'].fillna("D")


In [10]:
train_set.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [11]:
#  taking care of categorical data
test_set.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [12]:
test_set['Age'] = train_set['Age'].fillna(train_set['Age'].mean())
test_set['Fare'] = train_set['Fare'].fillna(train_set['Fare'].mean())

In [13]:
#  taking care of categorical data
test_set.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [14]:
train_set

Survived  Pclass     Sex        Age  SibSp  Parch      Fare Embarked
0           0       3    male  22.000000      1      0    7.2500        S
1           1       1  female  38.000000      1      0   71.2833        C
2           1       3  female  26.000000      0      0    7.9250        S
3           1       1  female  35.000000      1      0   53.1000        S
4           0       3    male  35.000000      0      0    8.0500        S
5           0       3    male  29.699118      0      0    8.4583        Q
6           0       1    male  54.000000      0      0   51.8625        S
7           0       3    male   2.000000      3      1   21.0750        S
8           1       3  female  27.000000      0      2   11.1333        S
9           1       2  female  14.000000      1      0   30.0708        C
10          1       3  female   4.000000      1      1   16.7000        S
11          1       1  female  58.000000      0      0   26.5500        S
12          0       3    male  20.000000      0      0    8.0500        S
13          0       3    male  39.000000      1      5   31.2750        S
14          0       3  female  14.000000      0      0    7.8542        S
15          1       2  female  55.000000      0      0   16.0000        S
16          0       3    male   2.000000      4      1   29.1250        Q
17          1       2    male  29.699118      0      0   13.0000        S
18          0       3  female  31.000000      1      0   18.0000        S
19          1       3  female  29.699118      0      0    7.2250        C
20          0       2    male  35.000000      0      0   26.0000        S
21          1       2    male  34.000000      0      0   13.0000        S
22          1       3  female  15.000000      0      0    8.0292        Q
23          1       1    male  28.000000      0      0   35.5000        S
24          0       3  female   8.000000      3      1   21.0750        S
25          1       3  female  38.000000      1      5   31.3875        S
26          0       3    male  29.699118      0      0    7.2250        C
27          0       1    male  19.000000      3      2  263.0000        S
28          1       3  female  29.699118      0      0    7.8792        Q
29          0       3    male  29.699118      0      0    7.8958        S
..        ...     ...     ...        ...    ...    ...       ...      ...
861         0       2    male  21.000000      1      0   11.5000        S
862         1       1  female  48.000000      0      0   25.9292        S
863         0       3  female  29.699118      8      2   69.5500        S
864         0       2    male  24.000000      0      0   13.0000        S
865         1       2  female  42.000000      0      0   13.0000        S
866         1       2  female  27.000000      1      0   13.8583        C
867         0       1    male  31.000000      0      0   50.4958        S
868         0       3    male  29.699118      0      0    9.5000        S
869         1       3    male   4.000000      1      1   11.1333        S
870         0       3    male  26.000000      0      0    7.8958        S
871         1       1  female  47.000000      1      1   52.5542        S
872         0       1    male  33.000000      0      0    5.0000        S
873         0       3    male  47.000000      0      0    9.0000        S
874         1       2  female  28.000000      1      0   24.0000        C
875         1       3  female  15.000000      0      0    7.2250        C
876         0       3    male  20.000000      0      0    9.8458        S
877         0       3    male  19.000000      0      0    7.8958        S
878         0       3    male  29.699118      0      0    7.8958        S
879         1       1  female  56.000000      0      1   83.1583        C
880         1       2  female  25.000000      0      1   26.0000        S
881         0       3    male  33.000000      0      0    7.8958        S
882         0       3  female  22.000000      0      0   10.5167        S
883      

In [15]:
test_set

Pclass     Sex        Age  SibSp  Parch      Fare Embarked
0         3    male  22.000000      0      0    7.2500        Q
1         3  female  38.000000      1      0   71.2833        S
2         2    male  26.000000      0      0    7.9250        Q
3         3    male  35.000000      0      0   53.1000        S
4         3  female  35.000000      1      1    8.0500        S
5         3    male  29.699118      0      0    8.4583        S
6         3  female  54.000000      0      0   51.8625        Q
7         2    male   2.000000      1      1   21.0750        S
8         3  female  27.000000      0      0   11.1333        C
9         3    male  14.000000      2      0   30.0708        S
10        3    male   4.000000      0      0   16.7000        S
11        1    male  58.000000      0      0   26.5500        S
12        1  female  20.000000      1      0    8.0500        S
13        2    male  39.000000      1      0   31.2750        S
14        1  female  14.000000      1      0    7.8542        S
15        2  female  55.000000      1      0   16.0000        C
16        2    male   2.000000      0      0   29.1250        Q
17        3    male  29.699118      0      0   13.0000        C
18        3  female  31.000000      1      0   18.0000        S
19        3  female  29.699118      0      0    7.2250        C
20        1    male  35.000000      1      0   26.0000        C
21        3    male  34.000000      0      1   13.0000        S
22        1  female  15.000000      0      0    8.0292        S
23        1    male  28.000000      0      1   35.5000        C
24        1  female   8.000000      1      3   21.0750        C
25        3    male  38.000000      1      0   31.3875        S
26        1  female  29.699118      0      1    7.2250        C
27        3    male  19.000000      0      0  263.0000        C
28        1    male  29.699118      0      0    7.8792        S
29        3    male  29.699118      2      0    7.8958        C
..      ...     ...        ...    ...    ...       ...      ...
388       3    male  29.699118      0      0    7.7292        Q
389       3    male  17.000000      3      1   12.0000        S
390       1    male  36.000000      0      0  120.0000        S
391       1  female  21.000000      0      1    7.7958        S
392       3    male  28.000000      0      2    7.9250        S
393       2    male  23.000000      0      0  113.2750        S
394       3    male  24.000000      3      1   16.7000        S
395       1  female  22.000000      1      0    7.7958        S
396       3    male  31.000000      0      0    7.8542        Q
397       1  female  46.000000      1      1   26.0000        C
398       3    male  23.000000      0      0   10.5000        S
399       3    male  28.000000      0      0   12.6500        Q
400       1  female  39.000000      0      0    7.9250        S
401       2    male  26.000000      1      0    8.0500        S
402       1  female  21.000000      0      1    9.8250        C
403       1    male  28.000000      0      0   15.8500        S
404       1    male  20.000000      1      0    8.6625        C
405       2    male  34.000000      0      0   21.0000        C
406       2    male  51.000000      1      0    7.7500        S
407       1    male   3.000000      1      1   18.7500        C
408       3  female  21.000000      0      0    7.7750        Q
409       3  female  29.699118      1      1   25.4667        S
410       3  female  29.699118      0      0    7.8958        Q
411       1  female  29.699118      1      0    6.8583        Q
412       3  female  33.000000      0      0   90.0000        S
413       3    male  29.699118      0      0    0.0000        S
414       1  female  44.000000      0      0    7.9250        C
415       3    male  29.699118      0      0    8.0500        S
416       3    male  34.000000      0      0   32.5000        S
417       3    male  18.000000      1      1   13.0000        C

[418 rows x 7 columns]

In [16]:
X = train_set.iloc[:,1:].values
Y= train_set.iloc[:,0].values

test = test_set.iloc[:, 0:].values

In [17]:
X

array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
       [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
       [3, 'female', 26.0, ..., 0, 7.925, 'S'],
       ...,
       [3, 'female', 29.69911764705882, ..., 2, 23.45, 'S'],
       [1, 'male', 26.0, ..., 0, 30.0, 'C'],
       [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [18]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])
X[:,6] = labelencoder_X.fit_transform(X[:,6])
onehotencoder1 = OneHotEncoder(categorical_features = [6])
X = onehotencoder1.fit_transform(X).toarray()


#encoding the categorical features in the test set
labelencoder_test = LabelEncoder()
test[:, 1] = labelencoder_test.fit_transform(test[:, 1])
test[:, 6] = labelencoder_test.fit_transform(test[:, 6])

onehotencoder2 = OneHotEncoder(categorical_features = [6])
test = onehotencoder2.fit_transform(test).toarray()


C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of

In [19]:
X

array([[ 0.    ,  0.    ,  0.    , ...,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    ,  0.    , ...,  1.    ,  0.    , 71.2833],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  0.    , ...,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 30.    ],
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    ,  7.75  ]])

In [20]:
test

array([[ 0.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  7.25  ],
       [ 0.    ,  0.    ,  1.    , ...,  1.    ,  0.    , 71.2833],
       [ 0.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    , 32.5   ],
       [ 1.    ,  0.    ,  0.    , ...,  1.    ,  1.    , 13.    ]])

In [21]:
#avoiding dummy variable trap
X = X[:, 1:]

X

array([[ 0.    ,  0.    ,  1.    , ...,  1.    ,  0.    ,  7.25  ],
       [ 0.    ,  0.    ,  0.    , ...,  1.    ,  0.    , 71.2833],
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  1.    , ...,  1.    ,  2.    , 23.45  ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 30.    ],
       [ 0.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  7.75  ]])

In [22]:
#avoiding dummy variable trap
#test = test[:, 1:]

test

array([[ 0.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  7.25  ],
       [ 0.    ,  0.    ,  1.    , ...,  1.    ,  0.    , 71.2833],
       [ 0.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    , 32.5   ],
       [ 1.    ,  0.    ,  0.    , ...,  1.    ,  1.    , 13.    ]])

In [23]:
#splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.1, random_state= 0)


In [24]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

test = sc_x.fit_transform(test)

In [25]:
test

array([[-5.68141541e-01,  2.84375747e+00, -1.35067551e+00, ...,
        -4.99470017e-01, -4.00247702e-01, -5.12929762e-01],
       [-5.68141541e-01, -3.51647429e-01,  7.40370278e-01, ...,
         6.16992373e-01, -4.00247702e-01,  7.86736157e-01],
       [-5.68141541e-01,  2.84375747e+00, -1.35067551e+00, ...,
        -4.99470017e-01, -4.00247702e-01, -4.99229476e-01],
       ...,
       [-5.68141541e-01, -3.51647429e-01,  7.40370278e-01, ...,
        -4.99470017e-01, -4.00247702e-01, -4.96692386e-01],
       [-5.68141541e-01, -3.51647429e-01,  7.40370278e-01, ...,
        -4.99470017e-01, -4.00247702e-01, -4.37598240e-04],
       [ 1.76012477e+00, -3.51647429e-01, -1.35067551e+00, ...,
         6.16992373e-01,  6.19895831e-01, -3.96223626e-01]])

In [26]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

regressor = LogisticRegression()
regressor.fit(X_train, Y_train)
Y_pred = regressor.predict(X_test)
acc_regressor = round(accuracy_score(Y_pred, Y_test) * 100, 2)
print(acc_regressor)

81.11


C:\Users\Dynamo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [27]:
Y_pred = regressor.predict(test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [28]:
log = pd.DataFrame({"PassengerId": test_sets["PassengerId"], "Survied": Y_pred})
log

PassengerId  Survied
0            892        0
1            893        0
2            894        0
3            895        0
4            896        0
5            897        0
6            898        0
7            899        0
8            900        1
9            901        0
10           902        0
11           903        0
12           904        1
13           905        0
14           906        1
15           907        1
16           908        1
17           909        0
18           910        0
19           911        1
20           912        0
21           913        0
22           914        1
23           915        1
24           916        1
25           917        0
26           918        1
27           919        0
28           920        0
29           921        0
..           ...      ...
388         1280        0
389         1281        0
390         1282        0
391         1283        1
392         1284        0
393         1285        0
394         1286        0
395         1287        1
396         1288        0
397         1289        1
398         1290        0
399         1291        0
400         1292        1
401         1293        0
402         1294        1
403         1295        0
404         1296        1
405         1297        0
406         1298        0
407         1299        1
408         1300        1
409         1301        0
410         1302        1
411         1303        1
412         1304        1
413         1305        0
414         1306        1
415         1307        0
416         1308        0
417         1309        0

[418 rows x 2 columns]

In [29]:
log = log.to_csv("log.csv", index = False)